### ISSUE TITLE
Request for Pretrained Model Weigths

### ISSUE THREAD

**Issue by yjwong1999** [Ayana-Inria/CRFNet-RS#1]
Hi @martinapastorino 

First of all, thank you so much for your open-source effort!
The repo is very well organized and documented, and I am excited to test it out!
Meanwhile, can you share the pretrained model weights?
I intended to use it for fast prototyping for my project based on this repo.

Hope to hear from you soon!

**Comment by martinapastorino** [comment]
Hi @yjwong1999, thank you very much for your interest! 

I added the weights of the model at this address <https://drive.google.com/drive/folders/1lUQ64GvajoYiQ8mrNQ2MUOpYD8sTdHhq?usp=sharing>, please find the additional info in the README. If you use this code, please cite the related paper.

If you happen to need more help, feel free to contact me!
